- name: play for prompt variables
  hosts: local
  connection: local

  vars_prompt:
    - name: COURSE
      prompt: Please enter the course name

    - name: DURATION
      prompt: Please enter the course Duration

    - name: TRAINER
      prompt: Please enter your trainer name

  tasks:
    - name: Print the prompt variables
      ansible.builtin.debug:
        msg: " Course is {{ COURSE }}, Duration: {{ DURATION }}, and trainer name is: {{ TRAINER }} "