- name: Play for variable preferences
  hosts:  local
  connection:  local

  # vars:
  #   GREET: PLAY
  # vars_files:
  #   - course.yaml
  # vars_prompt:
  #   - name: GREET
  #     prompt: Please enter you input
  #     private: false
  tasks:
    - name: task level variable
      # vars:
      #   GREET: Task
      ansible.builtin.debug:
        msg: "{{ GREET }}"


#1. Command line or args
#2. Task level
#3. Files
#4. Prompt
#5. Play
#6. Inventory


