- name: data types in Ansible
  hosts: local
  connection: local

  vars:
    course_name: "AWS DevSecOps" #String data type
    duration: 120 #number
    topics: # List data type
    - linux 
    - shell
    - ansible
    - AWS

    live: true # boolean
    tools:  # Map data type
      ci: jenkins
      clound: aws
      containerization: docker
  tasks:
    - name: Print course information
      ansible.builtin.debug:
        msg: "Hello I am learning {{ course_name }}, duration: {{ duration }}, topics are: {{ topics }}, is it live?: {{ live }}, tools covered are: {{ tools }}"
