- name: data types in Ansible
  hosts: local
  connection: local

  vars:
    course_name: "AWS DevSecOps"
    duration: 120
    topics:
    - linux
    - shell
    - ansible
    - AWS

    live: true
    tools:  
      ci: jenkins
      clound: aws
      containerization: docker
  tasks:
    - name: Print course information
      ansible.builtin.debug:
        msg: "Hello I am learning {{ course_name }}, duration: {{ duration }}, topics are: {{ topics }}, is it live?: {{ live }}, tools covered are: {{ tools }}"
