-   name: Install Packages
    hosts: web

    tasks:
    -   name:  installing package
        ansible.builtin.package:
            name: {{ item.name }}
            state:  {{ item.state }}
        loop:
        -   { name: "git", state: "present" }