-   name: Install Packages
    hosts: web
    become: yes

    tasks:
    - name: Installing Package
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      
      loop:
      - { name: "git", state: "present" }
      - { name: "mysql", state: "present" }
      - { name: "gcc", state: "absent" }
      - { name: "zip", state: "absent" }