- name: install nginx web server
  hosts: web
  become: yes

  tasks:
  - name: install nginx if it is RHEL
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx if it is Ubuntu
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family === "Debian"